language: node_js
sudo: required
node_js: 12.18.4
cache: npm
dist: trusty
addons:
  chrome: stable

git:
  depth: false
script:
  echo "Running AppShell default script"

# Define the stage sequence and conditionals
#
stages:
  - name:  Release
    if: commit_message =~ /\[release\]/

# Define stage implementation details
#
jobs:
  include:
    - stage: Release
      before_script: export NODE_OPTIONS='–--max_old_space_size=4096'
      script:
        - echo "######AAAAAAaa Deploying.and publishing..."
        - git checkout appshell
        - bash ./ci-scripts/setup-npm.sh
        - bash ./ci-scripts/publish-shell.sh
notifications:
  email:
    on_failure: always
    on_success: change
